[services]
solver = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
mediator = ["0x90F79bf6EB2c4f870365E785982E1f101E93b906"]

[web3]
rpc_url = "wss://devnet-chain-ws.lilypad.tech"
chain_id = 412346
controller_address = "0x4ed7c70F96B99c776995fB64377f0d4aB3B0e1C1"
payments_address = "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6"
storage_address = "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e"
users_address = "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82"
token_address = "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853"
mediation_address = "0x0B306BF915C4d645ff596e518fAf3F9669b97016"
jobcreator_address = "0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE"
pow_address = ""
